site_name: Kubernetes Fundamentals
pages:
  - Home: index.md
  - Provisioning VMs with Vagrant: "1_kube-cluster-vagrant.md"
  - Setup Kubernetes Cluster: "2_install_kubernetes.md"
  - Configuring Cluster: "3_configs.md"
  - Launching Pods: "4_deploying_pods.md"
  - Creating Deployments: "5_kubernetes_deployment.md"
  - Service Endpoints: "6_exposing_app_with_service.md"
  - Rollouts and Rollbacks: "7_rollouts-and-rollbacks.md"
  - Using Configmaps and Secrets: "8_using_configmaps_and_secrets.md"
  - Auto Scaling Capacity with HPA : "9_kubernetes_autoscaling.md"
  - Troubleshooting: "10_troubleshooting.md"
  - Mini Project: "11_deploying_sample_app.md"
docs_dir: tutorials
theme: readthedocs
